# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest, re

class TestLoginaddnote():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_loginaddnote(self):
    self.driver = webdriver.Firefox()
    self.driver.get("http://fitbit1.eastus.cloudapp.azure.com:8080/login")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".q-item:nth-child(1) .q-item__label--caption").click()
    source = self.driver.find_element_by_xpath("//input[@aria-label='Username']")
    source.send_keys("ana")
    source = self.driver.find_element_by_xpath("//input[@aria-label='Password']")
    source.send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".col-xs-12:nth-child(1) .q-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-xs-12:nth-child(1) .q-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,0)")
    time.sleep(5)
    self.driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/main/div[3]/div[2]/div/div[2]/label/div/div/div/input").click()
    self.driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/main/div[3]/div[2]/div/div[2]/label/div/div/div/input").send_keys("Coronavirus")
    self.driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/main/div[3]/div[2]/div/div[3]/label/div/div/div/textarea").click()
    self.driver.find_element_by_xpath("/html/body/div[1]/div/div[2]/main/div[3]/div[2]/div/div[3]/label/div/div/div/textarea").send_keys("flew")


    self.driver.find_element(By.CSS_SELECTOR, ".q-btn:nth-child(1) .q-btn__content > div").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".q-btn:nth-child(1) .q-btn__content > div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.execute_script("window.scrollTo(0,239)")
    self.driver.execute_script("window.scrollTo(0,429)")

if __name__ == '__main__':
        test = TestLoginaddnote()
        test.test_loginaddnote()
