version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "443:443"
      - "80:80"
      - "6899-6950:6899-6950"
    stdin_open: true
    tty: true
    depends_on:
      - db
  quasar:
    build: .
    command: bash -c "cd /code/fitbit_frontend && quasar dev"
    ports:
      - "8080:8080"
    volumes:
      - .:/code
