version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: apache2ctl -D FOREGROUND
    volumes:
      - .:/code
    ports:
      - "443:443"
      - "80:80"
      - "6899-6950:6899-6950"
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - db

