# Generated by Django 2.2.10 on 2020-02-05 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metric_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='fitbituser',
            name='is_specialist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='metric_manager.MetricsDescription'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='user_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_reader', to=settings.AUTH_USER_MODEL)),
                ('id_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_specialist', to=settings.AUTH_USER_MODEL)),
                ('user_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
